### ISSUE TITLE
Extract encoded metadata from Specimen and Experiment IDs

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#39]
Check for vocabulary 'codes' in the Specimen and Experiment IDs and make sure it is reflected in their respective FKRs to the vocabulary.

**Comment by svoinea** [comment]
[specimen_species.csv.zip](https://github.com/informatics-isi-edu/cirm-project/files/517344/specimen_species.csv.zip)

Attached the file with the list of the `Specimen` ids which have no values for the `Species`, `Tissue`, `Gene` and `Age` columns.

**Comment by robes** [comment]
There are definitely variations that we can note like: ‘h’, ‘Hu’ for human, ‘Kid’ or ‘KID’ for kidney, and clearly ‘mouse’. That would cover a few, but the rest are not as obvious.

**Comment by svoinea** [comment]
[experiment_probe.csv.zip](https://github.com/informatics-isi-edu/cirm-project/files/520103/experiment_probe.csv.zip)
Attached also the file of the `Experiment` ids which have no values for the `Experiment Type` and `Probe` columns.

**Comment by svoinea** [comment]
Based on some guessing from the `ID` value, the `NULL` values were replaced with the terms from the vocabulary tables. When no match was found, those `NULL` values were replaced by the `Other` or `Unknown` terms. The operation of replacing the `NULL` values was necessary in order to set those fields as `required`, i.e. adding the `NOT NULL` constraint.
