### ISSUE TITLE
CIRM Cleanup

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/cirm-project#62]
On dashboard Cirm -> CIRM
In specimens, some of the age values are not correct, they still have unit indications in them.

In general, we should propagate the age naming scheme across all of the data, specifically scan. Actually, scan age should be consistent with (or even come from) the specimen age.

**Comment by svoinea** [comment]
The dashboard Cirm -> CIRM issue was fixed by using the `tag:misd.isi.edu,2015:display` annotation.
We preserved the pre-existed values of the `Specimen.Age`. That explains the inconsistency. Wherever it was possible, we converted them to the new model.
For the new values, we have now two distinct fields: `Age Value` and `Age Unit`. The `Specimen.Age` is automatically generated from the concatenation of the two.
The `Scan` table has now the `age` column that is propagated from `Specimen.Age`.
