### ISSUE TITLE
Fix probes columns and annotations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#63]
For example see
https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Experiment/ID=20150805-IFUPIII-GA-0

The page shows both Probe and Probes. Why do we show both? And for that matter we only annotate one (Probe).

**Comment by svoinea** [comment]
@robes In the old version we support multiple probes to be assigned, separated by comma. They are now gathered into an array.
If a single probe is assigned, then the array will have just one element.
The probe is now a vocabulary term, so it contains just the list of distinct terms, and no combination between them.
In the new version, I'm not sure if we will support multiple probes.
Anyway, at this time, we have experiments with multiple probes.

**Comment by svoinea** [comment]
The problem was fixed by using the `experiment_probe` association table.
The first defined probe is stored in the `Experiment.Probe` column.
Additional probes might be defined while updating the `Experiment` table.
They got stored in the `Experiment.Probes` column, and might be seen in the `compact` context of the `Experiment` table.
In the `detailed` context of the `Experiment` table, the probes might be seen through the `expriment_probe` association table.
