### ISSUE TITLE
Generate 'Print Label' link when fields are missing

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#83]
Handle more `NULL`s from the older Specimens (and Experiments).

**Comment by svoinea** [comment]
A number of 13 old specimens were detected as having `NULL` values for the `Label`. It was due to the fact that they had `NULL` values for the `comment` that is part of the `Label`. The `NULL` values were replaced by the empty string, and now no specimen has a `NULL` value for the `Label`.
For the `Slide`, I have checked and all the slides attached to an experiment have a non `NULL` value for the `Label`. Slides with no experiment attached to them have a `NULL` value for the `Label`.
