### ISSUE TITLE
Sync catalog to cirm-staging

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/cirm-project#9]

**Comment by svoinea** [comment]
A "persistent" cookie was created.

The catalog was created with the command:

```
curl -X POST "https://cirm-staging.isrd.isi.edu/ermrest/catalog"
```

The catalog was then renamed to `microscopy`.

A dump of the `Microscopy` schema was then collected from the production `spineynorman.hsc.usc.edu` CIRM server and loaded into the `cirm-staging` VM.

The ACL of `cirm-staging` includes currently the following groups:
- cirm-usc
- cirm-isi
- cirm

At the first login, a server error was encountered due to a permission. The statement:

```
GRANT USAGE ON SCHEMA _ermrest TO ermrest
```

was either not run during the catalog creation, either was lost during the catalog renaming.

Currently, the Microscopy client works as expected. 

Note:

```
The real host names of the production CIRM printers are not present in Github. 
If the webcli is re-installed, the "/var/www/html/webcli/js/app.js" file needs to be 
updated with those real names. 
The current "microscopy_webcli_install" is not doing that thing. 
```

For the `chaise`, the annotations define at this time just the `Microscopy` as the default schema and the `Experiment` as the default table. This is currently an open process.

**Comment by robes** [comment]
I don't really understand the context of this issue. Isn't the sync supposed to happen right before we do the switch over. I.e., step 1, we switch spiney into _read only_ mode; step 2 we do the sync, and step 3 we make cirm-staging available to them.
